version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./env/dev/mysql:/var/lib/mysql
            - ./env-config/mysql:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - 3306:3306
        restart: always
    redis:
        image: redis
        volumes:
            - ./env/dev/redis:/data
        ports:
            - 6379:6379
        restart: always